### ISSUE TITLE
Add average location of brain and spinal cord

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/phantom-spinoza#5]
In the context of research project https://github.com/spinal-cord-7t/coil-qc-code/issues/63#issuecomment-2142557387 we need the approximate location of the spinal cord. 

I remember we used the average spinal cord segmentation (across 20 subjects) for a related project, do we have the CAD design of the spinal cord surface? 

If not, do we have other means to approximate the spinal cord location? And ideally of the brain? If spinoza was based of an EM model (eg Hugo), then we should be able to extract this information relatively easily.

@NLopezRios

**Comment by NLopezRios** [comment]
Alexandru created a 3D probabilistic localization of the spinal cord across 22 subjects by segmenting images with SCT. I can look for the CAD of that region if it is useful. 
![image](https://github.com/neuropoly/phantom-spinoza/assets/119605699/c76b2be6-7d4a-4697-80c9-662f11a9b98e)

Spinoza was not based on the EM human models. It started as a simplified surface covering 5 of those 22 subjects, with focus on the neck. It was modified later to better approximate the human head size and Tx coil loading. If you want to use one of the human models, I would recommend Gustav, which better matches Spinoza.

**Comment by jcohenadad** [comment]
Thank you @NLopezRios. I'm afraid the SC mask does not go low enough. Moreover, doing the CAD to NIfTI conversion, and registration, will take some time. It will be faster to just draw an approximate spinal cord centerline programatically and then create a cylindrical mask around it @evaalonsoortiz
