### ISSUE TITLE
What recipe for v2

### ISSUE THREAD

**Issue by CharlesPageot** [neuropoly/phantom-spinoza#6]
For a project with shimming @4rnaudB would need to know the T1 of Spinoza v2 that is at UNF. @NLopezRios would you have the recipe for that version by any chance?

**Comment by NLopezRios** [comment]
Dielectric parameters @300MHz:

- Conductivity: 0.6 S/m
- Permittivity: 35.46

Recipe:

- Solvent: 960ml demineralized water + 40ml mouthwash
- Sugar: 1970g
- Salt: 253g
- Gadolinium: 1ml

**Comment by 4rnaudB** [comment]
Thank you!

**Comment by 4rnaudB** [comment]
> Dielectric parameters @300MHz:
> 
> * Conductivity: 0.6 S/m
> * Permittivity: 35.46
> 
> Recipe:
> 
> * Solvent: 960ml demineralized water + 40ml mouthwash
> * Sugar: 1970g
> * Salt: 253g
> * Gadolinium: 1ml
